comment:
  footer: "\
    ----\n\n
    > *This is an automated response created by a **GitHub Action***\n
    > *Mentioning the bot won't have any effect!*
    "

labels:
  - name: 'Type: Issue (Expansion)'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},
          
          The issue you encountered is caused by an Expansion and not PlaceholderAPI itself.
          This issue-tracker is reserved for Bug reports and feature requests towards PlaceholderAPI.
          
          Please report this issue to the Expansion's main issue-tracker.
        action: close
  - name: 'Type: Duplicate'
    labeled:
      issue:
        body: |-
          Your issue is already known and a separate issue with the exact same report/feature request already exist.
          
          Please comment on the already existing issue with your information instead of opening your own.
        action: close
  - name: 'Problem: More info required'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},
          
          Your issue unfortunately lacks certain information that we require in order to help you with your issue.
          Please make sure you provide the following information:
          
          - Currently used Versions of your server and PlaceholderAPI
          - Currently installed Expansions
          - Currently installed Plugins
          
          The easiest way to provide those information is through the `/papi dumb` command which posts the required information to https://paste.helpch.at and gives a URL to share.
    unlabeled:
      issue:
        body: |-
          Thank you for providing additional information.
          We will take a look at the issue you encounter and come back to you with a possible solution.
  - name: 'Type: Invalid'
    labeled:
      issue:
        body: |-
          Your issue has beeen marked as invalid.
          This means that it either doesn't follow any provided template, or isn't related to PlaceholderAPI in any way.
          
          Please make sure to use one of the issue templates and provide the requested information.
          Currently available Templates are:
          
          - [Bug Report](https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=bug_report.md)
          - [Feature Request](https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=feature_request.md)
          
          If you want changes to be made towards the Wiki, would we encourage you to [Make a Pull request](https://github.com/PlaceholderAPI/PlaceholderAPI/pulls).  
          You can find more information about this process on the [Wiki's Readme](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/wiki/README.md).
          
          It is recommended to [join our Discord Server](https://helpch.at/discord) as you often receive faster response compared to the issue tracker here.
          Questions about PlaceholderAPI should be asked in our [Discussions](https://github.com/PlaceholderAPI/PlaceholderAPI/discussions).
        action: close
      pull_request:
        body: |-
          Your Pull Request has been marked as invalid.
          This means that it doesn't follow our [Contributing Guidelines](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/.github/CONTRIBUTING.md).
          
          Here is a small summary of what you should know:
          
          - Pull requests for PlaceholderAPI should target the `develop` branch.
          - Pull requests for the Wiki should target the `docs/wiki` branch.
          
          Don't hesitate to ask us any questions.
        action: close
  - name: 'Target: Wiki'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},
          
          Thank you for reaching out to us about the wiki.
          We would like to inform you, that you are now able to directly commit your changes to the wiki through a Pull request.
          When doing so, make sure you follow these steps:
          
          - The Pull request targets the [`docs/wiki`](https://github.com/PlaceholderAPI/PlaceholderAPI/tree/docs/wiki) branch of the Repository.
          - You only made changes to the files inside the `wiki` folder.
          - You followed the general Styling Guidelines mentioned in the wiki's [README](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/docs/wiki/wiki/README.md) file.
          
          If you have any questions about submitting a PR for the wiki or have any other questions don't hesitate to ask us about it.
  - name: 'Type: Not a bug'
    labeled:
      issue:
        body: |-
          The issue you encounter is not considered a bug and rather an intentional behaviour of PlaceholderAPI and/or one of its expansions.
          If you still believe that it is a bug, provide more information and a maintainer of this repository may look at it more closely.
          
          Before providing more info, always make sure to use the latest version of PlaceholderAPI, as the issue you encounter might already be fixed in a newer version.
          Optionally can you also try out [development builds](https://ci.extendedclip.com/job/PlaceholderAPI/) and see if the issue was fixed there.
        action: close
    unlabeled:
      issue:
        body: After further investigation is the issue you encounter indeed considered a bug and we will try to fix it as soon as possible.
        action: open
  - name: 'Status: Inactive'
    labeled:
      issue:
        body: |-
          The issue was marked as "inactive" which means it didn't recieve any responses from the Author ({{ issue.user.login }}) for a long period of time.
          To keep the issue-tracker clean and up to date are we closing issues, that didn't receive any responses for a long time.
          
          If you're the Author and this issue is still present, make sure to respond with extra info and **do not create a new issue for the same problem!**
        action: close
    unlabeled:
      issue:
        body: The issue received a response from the Author who confirms this to still be prominent and has therefore been reopened.
        action: open
  - name: 'Type: Question'
    labeled:
      issue:
        body: |-
          Hello @{{ issue.user.login }},
          
          Thank you for reaching out to us for getting Support with PlaceholderAPI.
          We would like to inform you, that we now have [Discussions](https://github.com/PlaceholderAPI/PlaceholderAPI/discussions) that you can use for asking questions.
          Just head over there and click the "New discussion" button to create a new post.
          
          Remember to first read the [READ ME](https://github.com/PlaceholderAPI/PlaceholderAPI/discussions/507) post to not face any issues.
          
          For questions do we recommend to use the [Q&A Category](https://github.com/PlaceholderAPI/PlaceholderAPI/discussions?discussions_q=category%3AQ%26A).
          You can also use the Discussion to submit Feature requests (Feature requests through issues are still accepted tho).
