blank_issues_enabled: false
contact_links:
  - name: HelpChat Discord
    url: https://discordapp.com/invite/0utOOIYX82aImw7h
    about: Please join our Discord for faster support.
  - name: Wiki
    url: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki
    about: The Wiki of PlaceholderAPI.
  - name: Hastebin
    url: https://paste.helpch.at
    about: Use our Hastebin-site for sharing errors and configuration files.
